### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by cmolleur** [cmolleur/groove#5]
I have the code implemented, but I'm getting a ton of errors.

**Comment by rapala61** [comment]
Try changing:

``` js
app.listen( port, function(){
  console.log( 'Free margaritas on Port:8080' );
});
```

for 

``` js
http.listen( port, function(){
  console.log( 'Free margaritas on Port:8080' );
});
```

In your `app.js` file

**Comment by rapala61** [comment]
You should also take a look at my implementation of a multi-room chat here: https://github.com/rapala61/multichat_sample
